/******************************************************************************
 * Copyright (c) 2012 Sergey Alexandrov
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 ******************************************************************************/

#ifndef PMD_CAMBOARD_NANO_H
#define PMD_CAMBOARD_NANO_H

#include <string>

#include <boost/scoped_ptr.hpp>
#include <boost/lexical_cast.hpp>

#include <ros/time.h>
#include <sensor_msgs/distortion_models.h>
#include <sensor_msgs/CameraInfo.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/PointCloud2.h>

#include <pmdsdk2.h>

#ifndef PMD_PLUGIN_DIR
  #error PMD_PLUGIN_DIR should be defined
#endif

namespace pmd_camboard_nano
{

class PMDCamboardNano
{

public:

  typedef boost::shared_ptr<PMDCamboardNano> Ptr;

  /** Try to open a PMD camera with a given serial number.
    *
    * If the serial number is an empty string, then the first available camera
    * will be opened. The PMD SDK driver tends to open any available camera if
    * the camera with the specified serial number is not present. If this
    * happens, the constructor will close the opened camera and assume that the
    * requested camera is not available.
    *
    * An exception will be thrown if it is not possible to open the camera. */
  PMDCamboardNano(const std::string& device_serial = "");

  virtual ~PMDCamboardNano();

  /** Download the most recent data from the device.
    *
    * This function should be called before getDepthImage(),
    * getAmplitudeImage(),  or getCameraInfo(), otherwise they will return the
    * old data.
    *
    * An exception will be thrown if the interaction with the device failed. */
  void update();

  /** Get the distance data packaged in a ROS image message.
    *
    * The contained data represent the distances between the camera and the
    * objects that the respective pixels observe.
    *
    * Two subsequent calls to this function will return the same images with
    * the same timestamps unless update() is called in between.
    *
    * This function may treat the invalid pixels differently, see
    * setRemoveInvalidPixels().
    *
    * Note: the output message has a blank frame_id field. */
  sensor_msgs::ImagePtr getDistanceImage();

  /** Get the depth data packaged in a ROS image message.
    *
    * The contained data represent the coordinates of the scene points along
    * the optical axis in the cameras frame. In other words, these are the
    * distance data projected on the optical axis.
    *
    * Two subsequent calls to this function will return the same images with
    * the same timestamps unless update() is called in between.
    *
    * This function may treat the invalid pixels differently, see
    * setRemoveInvalidPixels().
    *
    * Note: the output message has a blank frame_id field. */
  sensor_msgs::ImagePtr getDepthImage();

  /** Get the signal strength of active illumination packaged in a ROS image
    * message.
    *
    * Two subsequent calls to this function will return the same images with
    * the same timestamps unless update() is called in between.
    *
    * This function may treat the invalid pixels differently, see
    * setRemoveInvalidPixels().
    *
    * Note: the output message has a blank frame_id field. */
  sensor_msgs::ImagePtr getAmplitudeImage();

  /** Get the point cloud generated by the driver and packaged in a ROS point
    * cloud message.
    *
    * Two subsequent calls to this function will return the same point clouds
    * with the same timestamps unless update() is called in between.
    *
    * This function may treat the invalid pixels differently, see
    * setRemoveInvalidPixels().
    *
    * Note: the output message has a blank frame_id field. */
  sensor_msgs::PointCloud2Ptr getPointCloud();

  /** Get camera calibration parameters packaged in a ROS camera info message.
    *
    * If the driver failed to load the calibration data from file, the message
    * will only have correct width and height fields, and the rest will be set
    * to zeros.
    *
    * The update() function should be called before this one.
    *
    * Note: the output message has a blank frame_id field. */
  sensor_msgs::CameraInfoPtr getCameraInfo();

  /** Load calibration data from the given file.
    *
    * @return a flag indicating whether the file was successfully loaded. */
  bool loadCalibrationData(const std::string& filename);

  /** Check whether the calibration data file was loaded. */
  bool isCalibrationDataLoaded();

  /** Get the serial number of the opened PMD camera. */
  std::string getSerialNumber();

  /** Set an internal flag which controls whether the invalid pixels are
    * are filtered out from the output images/point clouds.
    *
    * Setting this flag affects the behavior of getDistanceImage(),
    * getDepthImage(), getAmplitudeImage(), and getPointCloud(). If the flag is
    * not set, the depth/amplitude images returned by those functions will
    * contain all of the data received from the camera. If the flag is set, the
    * camera will be additionally queried for the "flags" array that describes
    * which of the pixels are invalid. These pixels will be replaced with quiet
    * NaNs in the output data.
    *
    * By default the flag is set to true. */
  void setRemoveInvalidPixels(bool remove)
  {
    remove_invalid_pixels_ = remove;
  }

  /** Set an internal flag which controls whether the images/point clouds read
    * from the camera should be flipped vertically.
    *
    * Setting this flag affects the behavior of getDistanceImage(),
    * getDepthImage(), getAmplitudeImage(), and getPointCloud(). If the flag is
    * not set, then the data are exactly what is received from the camera. If
    * the flag is set, then the data is flipped vertically, i.e. the first row
    * is swapped with the last, the second row is swapped with the second last
    * and so on.
    *
    * By default the flag is set to true. */
  void setFlipVertical(bool flip)
  {
    flip_vertical_ = flip;
  }

  /** Get current integration time (us). */
  unsigned int getIntegrationTime();

  /** Set integration time (us).
    *
    * Not all integration times are valid settings. This function will first
    * query the camera to find the closest valid value for integration time and
    * then set it.
    *
    * @return coerced integration time */
  unsigned int setIntegrationTime(unsigned int time);

  /** Get the number of frames of in the temporal sliding averaging window.
    *
    * If the averaging is disabled this function outputs zero. */
  unsigned int getAveragingFrames();

  /** Set the number of frames of in the temporal sliding averaging window.
    *
    * Passing zero disables temporal averaging. */
  void setAveragingFrames(unsigned int frames);

  /** Enable/disable the signal strength check during the calculation of the
    * flag image. */
  void setSignalStrengthCheck(bool enable)
  {
    setProcessingPluginSetting("SetSignalStrengthCheck", enable);
  }

  /** Get the current threshold value for the signal strength check. */
  unsigned int getSignalStrengthThreshold()
  {
    return getProcessingPluginSetting<unsigned int>("GetSignalStrengthThreshold");
  }

  /** Set the amplitude threshold for the signal strength check.
    *
    * Higher values mean higher sensitivity and more pixels flagged invalid. */
  void setSignalStrengthThreshold(unsigned int amplitude)
  {
    setProcessingPluginSetting("SetSignalStrengthThreshold", amplitude);
  }

  /** Enable/disable the consistency check during the calculation of the flag
    * image.
    *
    * The raw data from the device will be analyzed for inconsistencies, such
    * as motion artifacts. */
  void setConsistencyCheck(bool enable)
  {
    setProcessingPluginSetting("SetConsistencyCheck", enable);
  }

  /** Get the current threshold value for the consistency check. */
  double getConsistencyThreshold()
  {
    return getProcessingPluginSetting<double>("GetConsistencyThreshold");
  }

  /** Set the consistency threshold for the consistency check.
    *
    * Valid range is between 0 and 1 and the argument will be clamped to this
    * range. Higher values mean higher consistency and data quality. */
  void setConsistencyThreshold(double threshold)
  {
    setProcessingPluginSetting("SetConsistencyThreshold", clamp(threshold, 0.0, 1.0));
  }

  /** Enable/disable bilateral filtering of the distances. */
  void setBilateralFilter(bool enable)
  {
    setProcessingPluginSetting("SetBilateralFilter", enable);
  }

  /** Set the spatial sigma parameter of the bilateral filter. */
  void setBilateralFilterSigmaSpatial(double sigma)
  {
    setProcessingPluginSetting("SetBilateralFilterSigmaSpatial", std::max(sigma, 0.01));
  }

  /** Set the range sigma parameter of the bilateral filter. */
  void setBilateralFilterSigmaRange(double sigma)
  {
    setProcessingPluginSetting("SetBilateralFilterSigmaRange", std::max(sigma, 0.01));
  }

  /** Set the kernel size of the bilateral filter mask. */
  void setBilateralFilterKernelSize(unsigned int size)
  {
    setProcessingPluginSetting("SetBilateralFilterKernelSize", std::max(size, (unsigned int)1));
  }

  /** Enable/disable enhanced bilateral filtering of the distances.
    *
    *  By incorporating precomputed flags into the bilateral filter it becomes
    *  more robust against motion blur. */
  void setBilateralFilterEnhanceImage(bool enable)
  {
    setProcessingPluginSetting("SetBilateralFilterEnhanceImage", enable);
  }

private:

  sensor_msgs::ImagePtr createImageMessage();

  sensor_msgs::PointCloud2Ptr createPointCloud2Message();

  void processData(float* data, size_t step, bool apply_direction_vectors, bool remove_invalid_pixels, bool flip_vertical);

  void getDirectionVectors();

  void setProcessingPluginSetting(const std::string& command, bool value);

  void setProcessingPluginSetting(const std::string& command, unsigned int value);

  void setProcessingPluginSetting(const std::string& command, double value);

  template<typename T>
  T getProcessingPluginSetting(const std::string& command)
  {
    char buffer[128];
    throwExceptionIfFailed(pmdProcessingCommand(handle_, buffer, sizeof(buffer), command.c_str()));
    return boost::lexical_cast<T>(buffer);
  }

  template<typename T>
  static T clamp(T value, T min, T max)
  {
    return value < min ? min : (value > max ? max : value);
  }

  void throwExceptionIfFailed(int result);

  PMDHandle handle_;

  unsigned int num_rows_;
  unsigned int num_columns_;
  unsigned int num_pixels_;

  bool remove_invalid_pixels_;
  bool flip_vertical_;

  boost::scoped_ptr<double> direction_vectors_;

  ros::Time last_update_time_;

};

}

#endif /* PMD_CAMBOARD_NANO_H */

